### ISSUE TITLE
Updating README

### ISSUE THREAD

**Issue by abirbhattacharya82** [abirbhattacharya82/dad-jokes-js#4]
As you can see the current README is not so attractive. I want a readme which will be visually attractive for others so that they can think of using this package, while on the other hand the readme should also contain the following details as well.
- About
- Installation
- Usage

**Comment by Ankitrai2204** [comment]
Hello I want to contribute on this project. Can you please assign it to me and tell about our requirements.

**Comment by abirbhattacharya82** [comment]
Hey @Ankitrai2204 I assigned you this issue, the requirements are stated above in the issue details make sure not to leave those three things. Apart from that go creative
